version: "3.7"

networks:
  data:
    driver: bridge

  web:
    driver: bridge

services:
  mongo:
    container_name: ${APP_TITLE}-${DB_NAME}
    image: ${APP_TITLE}/mongo
    build:
      context: .
      dockerfile: ./config/${NODE_ENV}/mongo.dockerfile
    labels:
      com.kidmngr.db: ${DB_NAME}
      com.kidmngr.description: "NoSQL database"
      com.kidmngr.maintainer: ${MAINTAINER}
      com.kidmngr.email: ${EMAIL}
    command: "--auth"
    expose: 
      - ${DB_PORT}
    volumes:
      - ${LOCAL_PATH}:${DB_PATH}:rw
    logging:
      options:
        max-size: "50k"
        max-file: "2"
    networks:
      - data

  api:
    container_name: ${APP_TITLE}-api
    image: node:10.16.3
    labels:
      com.kidmngr.api: "api"
      com.kidmngr.description: "Main API endpoint"
      com.kidmngr.maintainer: ${MAINTAINER}
      com.kidmngr.email: ${EMAIL}
    depends_on:
      - mongo
    ports:
      - "${API_PORT}:3000"
    env_file:
      - ./config/${NODE_ENV}/api.env
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - "./api/dev/:/usr/app/"
      - "./api/node_modules/:/usr/app/node_modules/"
      - "./.ignored/alipay:/usr/app/assets/alipay"
      - "./public:/public"
    working_dir: "/usr/app"
    command: node bundle.js
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "2"
    networks:
      - data
      - web

  consumer:
    container_name: ${APP_TITLE}-consumer
    image: nginx
    labels:
      com.kidmngr.consumer: ${APP_TITLE}
      com.kidmngr.description: "consumer frontend"
      com.kidmngr.maintainer: ${MAINTAINER}
      com.kidmngr.email: ${EMAIL}
    depends_on:
      - api
    ports: 
      - "${CONSUMER_WEBAPP_PORT}:80"
    volumes:
      - "./consumer/dev:/usr/share/nginx/html"
    working_dir: "/usr/share/nginx/html"
    networks:
      - data
      - web
